### PR TITLE
[dependency upgrades] Poison replaced with jason and httpoison upgrade

### PR DESCRIPTION
**Pull request by izelnakri**

### CODE REVIEW

**Comment by ayrat555** [comment]
Is there any benefit of using Jason over Poison?

**Comment by izelnakri** [comment]
Yes allegedly its faster and used instead of poison on ecto v3

**Comment by InoMurko** [comment]
Is Poison used more then Jason? If yes, that would mean most project that include exthereum as a dependency would now have two json encoders/decoders. The PR should rather chose an approach that would make the project independent of a particular choice.

**Comment by hayesgm** [comment]
It would be great for us to benchmark. The only concern is that projects that use this are now likely going to pull in a second JSON parsing library (or, on the other hand, go from two to one...)

**Comment by InoMurko** [comment]
What if we do something like Phoenix does with pluggable decoders? 
https://github.com/elixir-plug/plug/blob/master/lib/plug/parsers.ex#L271

**Comment by InoMurko** [comment]
Did a quick research and found out that Credo has jason as a dependency. Which means most projects that use Credo (like OmiseGO ewallet and OMG Network), will have Jason already there.

**Pull request merged**
