### PR TITLE
Add EIP1559 support for eth_maxPriorityFeePerGas and eth_feeHistory

### PR DESCRIPTION
**Pull request by akramhussein**
This PR adds support for `eth_maxPriorityFeePerGas` and `eth_feeHistory` which were added during the London fork for EIP1559 support.

[Reference](https://github.com/ethereum/pm/issues/328)

### CODE REVIEW

**Review by InoMurko — APPROVED** [review]

**Comment by akramhussein** [comment]
Tests are also wrong on the `eth_fee_history` RPC call. Fixing now.

**Comment by akramhussein** [comment]
> Tests are also wrong on the `eth_fee_history` RPC call. Fixing now.

Done

**Review by ayrat555 — APPROVED** [review]

**Comment by ayrat555** [comment]
@akramhussein thank you for your contribution.

your changes were released in 0.10.0.

I skipped your tests for now. we need to improve our ci 

I remember @rupurt was working on this in https://github.com/mana-ethereum/ethereumex/pull/106. so how it's going? 😄

**Comment by akramhussein** [comment]
Thanks!

**Pull request merged**
